services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: kotan-frontend
    restart: unless-stopped
    networks:
      - kotan-backend_inside

networks:
  kotan-backend_inside:
    external: true
